In [2]:
import pandas as pd
import pm4py
import json

In [5]:
log = pm4py.read_xes("../data/BPI Challenge 2017.xes.gz")

df = pm4py.convert_to_dataframe(log)
print(f"Loaded {len(df)} events.")

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pm4py/utils.py:986: UserWarning: In the current version, the import/export operation uses `rustxes` by default for importing/exporting files faster. Please uninstall `rustxes` to revert the behavior.
  warnings.warn("In the current version, the import/export operation uses `rustxes` by default for importing/exporting files faster. Please uninstall `rustxes` to revert the behavior.")

Loaded 1202267 events.

In [6]:
df.head()

,MonthlyCost,case:LoanGoal,OfferID,org:resource,NumberOfTerms,CreditScore,case:ApplicationType,Selected,case:concept:name,EventID,concept:name,FirstWithdrawalAmount,time:timestamp,EventOrigin,Accepted,case:RequestedAmount,OfferedAmount,Action,lifecycle:transition
0,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,Application_652823628,A_Create Application,NaN,2016-01-01 09:51:15.304000+00:00,Application,None,20000.0,NaN,Created,complete
1,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,ApplState_1582051990,A_Submitted,NaN,2016-01-01 09:51:15.352000+00:00,Application,None,20000.0,NaN,statechange,complete
2,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,Workitem_1298499574,W_Handle leads,NaN,2016-01-01 09:51:15.774000+00:00,Workflow,None,20000.0,NaN,Created,schedule
3,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,Workitem_1673366067,W_Handle leads,NaN,2016-01-01 09:52:36.392000+00:00,Workflow,None,20000.0,NaN,Deleted,withdraw
4,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,Workitem_1493664571,W_Complete application,NaN,2016-01-01 09:52:36.403000+00:00,Workflow,None,20000.0,NaN,Created,schedule

In [8]:
#Filter only for completed events
if 'lifecycle:transition' in df.columns:
    df = df[df['lifecycle:transition'].str.lower() == 'complete']
df.head()

,MonthlyCost,case:LoanGoal,OfferID,org:resource,NumberOfTerms,CreditScore,case:ApplicationType,Selected,case:concept:name,EventID,concept:name,FirstWithdrawalAmount,time:timestamp,EventOrigin,Accepted,case:RequestedAmount,OfferedAmount,Action,lifecycle:transition
0,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,Application_652823628,A_Create Application,NaN,2016-01-01 09:51:15.304000+00:00,Application,None,20000.0,NaN,Created,complete
1,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,ApplState_1582051990,A_Submitted,NaN,2016-01-01 09:51:15.352000+00:00,Application,None,20000.0,NaN,statechange,complete
5,NaN,Existing loan takeover,None,User_1,NaN,NaN,New credit,None,Application_652823628,ApplState_642383566,A_Concept,NaN,2016-01-01 09:52:36.413000+00:00,Application,None,20000.0,NaN,statechange,complete
8,NaN,Existing loan takeover,None,User_52,NaN,NaN,New credit,None,Application_652823628,ApplState_99568828,A_Accepted,NaN,2016-01-02 11:23:04.299000+00:00,Application,None,20000.0,NaN,statechange,complete
9,498.29,Existing loan takeover,None,User_52,44.0,979.0,New credit,True,Application_652823628,Offer_148581083,O_Create Offer,20000.0,2016-01-02 11:29:03.994000+00:00,Offer,True,20000.0,20000.0,Created,complete

In [11]:
#Now df is sorted by time and case
df = df.sort_values(by=['case:concept:name', 'time:timestamp'])
df.head(20)

,MonthlyCost,case:LoanGoal,OfferID,org:resource,NumberOfTerms,CreditScore,case:ApplicationType,Selected,case:concept:name,EventID,concept:name,FirstWithdrawalAmount,time:timestamp,EventOrigin,Accepted,case:RequestedAmount,OfferedAmount,Action,lifecycle:transition
686058,NaN,"Other, see explanation",None,User_1,NaN,NaN,New credit,None,Application_1000086665,Application_1000086665,A_Create Application,NaN,2016-08-03 15:57:21.673000+00:00,Application,None,5000.0,NaN,Created,complete
686059,NaN,"Other, see explanation",None,User_1,NaN,NaN,New credit,None,Application_1000086665,ApplState_161925113,A_Submitted,NaN,2016-08-03 15:57:21.734000+00:00,Application,None,5000.0,NaN,statechange,complete
686063,NaN,"Other, see explanation",None,User_1,NaN,NaN,New credit,None,Application_1000086665,ApplState_385184570,A_Concept,NaN,2016-08-03 15:58:28.299000+00:00,Application,None,5000.0,NaN,statechange,complete
686066,NaN,"Other, see explanation",None,User_5,NaN,NaN,New credit,None,Application_1000086665,ApplState_856156982,A_Accepted,NaN,2016-08-05 13:57:07.419000+00:00,Application,None,5000.0,NaN,statechange,complete
686067,241.28,"Other, see explanation",None,User_5,22.0,0.0,New credit,False,Application_1000086665,Offer_410892064,O_Create Offer,5000.0,2016-08-05 13:59:57.320000+00:00,Offer,True,5000.0,5000.0,Created,complete
686068,NaN,"Other, see explanation",Offer_410892064,User_5,NaN,NaN,New credit,None,Application_1000086665,OfferState_2071773136,O_Created,NaN,2016-08-05 13:59:58.162000+00:00,Offer,None,5000.0,NaN,statechange,complete
686069,NaN,"Other, see explanation",Offer_410892064,User_5,NaN,NaN,New credit,None,Application_1000086665,OfferState_388269514,O_Sent (mail and online),NaN,2016-08-05 14:01:23.264000+00:00,Offer,None,5000.0,NaN,statechange,complete
686073,NaN,"Other, see explanation",None,User_5,NaN,NaN,New credit,None,Application_1000086665,ApplState_1103800866,A_Complete,NaN,2016-08-05 14:01:23.288000+00:00,Application,None,5000.0,NaN,statechange,complete
686077,NaN,"Other, see explanation",None,User_1,NaN,NaN,New credit,None,Application_1000086665,ApplState_544389273,A_Cancelled,NaN,2016-09-05 06:00:36.710000+00:00,Application,None,5000.0,NaN,statechange,complete
686078,NaN,"Other, see explanation",Offer_410892064,User_1,NaN,NaN,New credit,None,Application_1000086665,OfferState_1258287612,O_Cancelled,NaN,2016-09-05 06:00:36.829000+00:00,Offer,None,5000.0,NaN,statechange,complete
445739,NaN,Home improvement,None,User_1,NaN,NaN,New credit,None,Application_1000158214,Application_1000158214,A_Create Application,NaN,2016-06-02 10:14:26.844000+00:00,Application,None,12500.0,NaN,Created,complete
445740,NaN,Home improvement,None,User_1,NaN,NaN,New credit,None,Application_1000158214,ApplState_277536765,A_Submitted,NaN,2016-06-02 10:14:26.885000+00:00,Application,None,12500.0,NaN,statechange,complete
445744,NaN,Home improvement,None,User_1,NaN,NaN,New credit,None,Application_1000158214,ApplState_1547990892,A_Concept,NaN,2016-06-02 10:15:36.773000+00:00,Application,None,12500.0,NaN,statechange,complete
445746,NaN,Home improvement,None,User_32,NaN,NaN,New credit,None,Application_1000158214,ApplState_226397461,A_Accepted,NaN,2016-06-06 08:10:07.694000+00:00,Application,None,12500.0,NaN,statechange,complete
445747,250.00,Home improvement,None,User_32,57.0,929.0,New credit,True,Application_1000158214,Offer_927137349,O_Create Offer,0.0,2016-06-06 08:12:02.402000+00:00,Offer,True,12500.0,12500.0,Created,complete
445748,NaN,Home improvement,Offer_927137349,User_32,NaN,NaN,New credit,None,Application_1000158214,OfferState_268883758,O_Created,NaN,2016-06-06 08:12:03.657000+00:00,Offer,None,12500.0,NaN,statechange,complete
445749,NaN,Home improvement,Offer_927137349,User_32,NaN,NaN,New credit,None,Application_1000158214,OfferState_1948801867,O_Sent (mail and online),NaN,2016-06-06 08:16:46.835000+00:00,Offer,None,12500.0,NaN,statechange,complete
445750,NaN,Home improvement,None,User_32,NaN,NaN,New credit,None,Application_1000158214,Workitem_518835990,W_Complete application,NaN,2016-06-06 08:16:46.869000+00:00,Workflow,None,12500.0,NaN,Deleted,complete
445753,NaN,Home improvement,None,User_32,NaN,NaN,New credit,None,Application_1000158214,ApplState_658801120,A_Complete,NaN,2016-06-06 08:16:46.892000+00:00,Application,None,12500.0,NaN,statechange,complete
445758,NaN,Home improvement,None,User_118,NaN,NaN,New credit,None,Application_1000158214,ApplState_1806387445,A_Validating,NaN,2016-06-09 09:54:36.870000+00:00,Application,None,12500.0,NaN,statechange,complete

Finding which activities are end activities?

In [25]:
#New column for the next activity
df['next_activity'] = df.groupby('case:concept:name')['concept:name'].shift(-1)
next_activity_none = df[df['next_activity'].isna()]
end_events = next_activity_none
print(next_activity_none['concept:name'].value_counts().head(10))

concept:name
O_Cancelled                 14051
A_Pending                   10288
W_Validate application       4036
O_Refused                    1977
W_Call incomplete files       631
W_Call after offers           135
A_Cancelled                   119
W_Assess potential fraud       93
W_Complete application         63
A_Complete                     30
Name: count, dtype: int64

Filter the rows where there isn't a next_activity available (end activity) NaN

In [35]:
transitions = df.dropna(subset=['next_activity'])
transitions['next_activity'].isna().sum()

np.int64(0)

What are the lines where the activity (concept:name) == next_activity --> loops

In [43]:
self_loops = transitions[transitions['concept:name'] == transitions['next_activity']]
num_of_self_loops = len(self_loops)
num_of_self_loops

8676

In [48]:
cols_to_show = ['case:concept:name', 'concept:name', 'lifecycle:transition', 'next_activity']
check_df = self_loops.copy()
check_df['next_lifecycle'] = df.groupby('case:concept:name')['lifecycle:transition'].shift(-1)
check_df[cols_to_show + ['next_lifecycle']]

,case:concept:name,concept:name,lifecycle:transition,next_activity,next_lifecycle
45028,Application_1000691650,O_Sent (mail and online),complete,O_Sent (mail and online),complete
45043,Application_1000691650,O_Sent (mail and online),complete,O_Sent (mail and online),complete
45046,Application_1000691650,O_Cancelled,complete,O_Cancelled,complete
45047,Application_1000691650,O_Cancelled,complete,O_Cancelled,complete
45048,Application_1000691650,O_Cancelled,complete,O_Cancelled,complete
...,...,...,...,...,...
1084755,Application_999464866,O_Cancelled,complete,O_Cancelled,complete
1084756,Application_999464866,O_Cancelled,complete,O_Cancelled,complete
373773,Application_999544538,O_Cancelled,complete,O_Cancelled,complete
373774,Application_999544538,O_Cancelled,complete,O_Cancelled,complete
373775,Application_999544538,O_Cancelled,complete,O_Cancelled,complete

In [49]:
print(self_loops['concept:name'].value_counts())

concept:name
O_Cancelled                 4429
O_Sent (mail and online)    3111
O_Refused                    975
O_Sent (online only)          85
O_Returned                    65
W_Assess potential fraud       5
W_Validate application         3
A_Incomplete                   3
Name: count, dtype: int64

In order to prevent that log learn from the self repeating loops (O_Cancelled -> O_Cancelled), these must be filtered out.

In [50]:
branching_transitions = transitions[transitions['concept:name'] != transitions['next_activity']]
branching_transitions

,MonthlyCost,case:LoanGoal,OfferID,org:resource,NumberOfTerms,CreditScore,case:ApplicationType,Selected,case:concept:name,EventID,concept:name,FirstWithdrawalAmount,time:timestamp,EventOrigin,Accepted,case:RequestedAmount,OfferedAmount,Action,lifecycle:transition,next_activity
686058,NaN,"Other, see explanation",None,User_1,NaN,NaN,New credit,None,Application_1000086665,Application_1000086665,A_Create Application,NaN,2016-08-03 15:57:21.673000+00:00,Application,None,5000.0,NaN,Created,complete,A_Submitted
686059,NaN,"Other, see explanation",None,User_1,NaN,NaN,New credit,None,Application_1000086665,ApplState_161925113,A_Submitted,NaN,2016-08-03 15:57:21.734000+00:00,Application,None,5000.0,NaN,statechange,complete,A_Concept
686063,NaN,"Other, see explanation",None,User_1,NaN,NaN,New credit,None,Application_1000086665,ApplState_385184570,A_Concept,NaN,2016-08-03 15:58:28.299000+00:00,Application,None,5000.0,NaN,statechange,complete,A_Accepted
686066,NaN,"Other, see explanation",None,User_5,NaN,NaN,New credit,None,Application_1000086665,ApplState_856156982,A_Accepted,NaN,2016-08-05 13:57:07.419000+00:00,Application,None,5000.0,NaN,statechange,complete,O_Create Offer
686067,241.28,"Other, see explanation",None,User_5,22.0,0.0,New credit,False,Application_1000086665,Offer_410892064,O_Create Offer,5000.0,2016-08-05 13:59:57.320000+00:00,Offer,True,5000.0,5000.0,Created,complete,O_Created
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918280,NaN,Caravan / Camper,None,User_42,NaN,NaN,New credit,None,Application_999993812,ApplState_326592771,A_Complete,NaN,2016-10-10 12:47:12.426000+00:00,Application,None,30000.0,NaN,statechange,complete,A_Validating
918287,NaN,Caravan / Camper,None,User_113,NaN,NaN,New credit,None,Application_999993812,ApplState_306039057,A_Validating,NaN,2016-10-19 10:28:04.832000+00:00,Application,None,30000.0,NaN,statechange,complete,O_Returned
918288,NaN,Caravan / Camper,Offer_913122697,User_113,NaN,NaN,New credit,None,Application_999993812,OfferState_1258740957,O_Returned,NaN,2016-10-19 10:28:11.487000+00:00,Offer,None,30000.0,NaN,statechange,complete,A_Incomplete
918293,NaN,Caravan / Camper,None,User_109,NaN,NaN,New credit,None,Application_999993812,ApplState_756087123,A_Incomplete,NaN,2016-10-19 12:44:29.292000+00:00,Application,None,30000.0,NaN,statechange,complete,O_Accepted
918297,NaN,Caravan / Camper,Offer_913122697,User_68,NaN,NaN,New credit,None,Application_999993812,OfferState_1927291643,O_Accepted,NaN,2016-10-24 06:24:30.056000+00:00,Offer,None,30000.0,NaN,statechange,complete,A_Pending

In [51]:
containing_any_self_loop = branching_transitions[branching_transitions['concept:name'] == branching_transitions['next_activity']]
len(containing_any_self_loop)

0

In [61]:
all_branching = branching_transitions.groupby(['concept:name', 'next_activity']).size().sort_values(ascending=False)
branching_df = all_branching.reset_index(name='count')
sorted_branching_df = branching_df.sort_values(by=['concept:name', 'count'], ascending=[True, False])
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(sorted_branching_df)

                 concept:name             next_activity  count
2                  A_Accepted            O_Create Offer  31504
125                A_Accepted    W_Complete application      3
129                A_Accepted  W_Assess potential fraud      2
15                A_Cancelled               O_Cancelled  10270
89                A_Cancelled   W_Call incomplete files     24
104               A_Cancelled       W_Call after offers     11
109               A_Cancelled    W_Complete application      7
8                  A_Complete              A_Validating  18339
16                 A_Complete               A_Cancelled   8034
24                 A_Complete            O_Create Offer   4135
49                 A_Complete               O_Cancelled    470
58                 A_Complete       W_Call after offers    202
64                 A_Complete                  A_Denied    108
78                 A_Complete  O_Sent (mail and online)     41
135                A_Complete      O_Sent (online only)      2
142                A_Complete  W_Assess potential fraud      1
3                   A_Concept                A_Accepted  31501
118                 A_Concept    W_Complete application      5
124                 A_Concept  W_Assess potential fraud      3
5        A_Create Application               A_Submitted  20423
13       A_Create Application                 A_Concept  11086
26                   A_Denied                 O_Refused   3720
117                  A_Denied       W_Call after offers      5
120                  A_Denied    W_Complete application      4
126                  A_Denied   W_Call incomplete files      3
149                  A_Denied    W_Validate application      1
11               A_Incomplete              A_Validating  12282
21               A_Incomplete                O_Accepted   4781
34               A_Incomplete   W_Call incomplete files   2053
36               A_Incomplete            O_Create Offer   1704
39               A_Incomplete                O_Returned   1168
46               A_Incomplete               A_Cancelled    737
59               A_Incomplete                  A_Denied    189
67               A_Incomplete               O_Cancelled     97
114              A_Incomplete      O_Sent (online only)      6
123              A_Incomplete  O_Sent (mail and online)      4
144              A_Incomplete       W_Call after offers      1
145              A_Incomplete  W_Assess potential fraud      1
27                  A_Pending               O_Cancelled   3529
30                  A_Pending    W_Validate application   3352
72                  A_Pending   W_Call incomplete files     59
10                A_Submitted                 A_Concept  16929
29                A_Submitted            W_Handle leads   3476
93                A_Submitted  W_Assess potential fraud     18
4                A_Validating                O_Returned  21542
18               A_Validating                O_Accepted   7136
22               A_Validating    W_Validate application   4488
23               A_Validating              A_Incomplete   4427
40               A_Validating                  A_Denied   1095
75               A_Validating            O_Create Offer     51
83               A_Validating               A_Cancelled     34
85               A_Validating  W_Assess potential fraud     32
111              A_Validating               O_Cancelled      7
141              A_Validating      O_Sent (online only)      1
9                  O_Accepted                 A_Pending  17228
45                O_Cancelled            O_Create Offer    753
48                O_Cancelled   W_Call incomplete files    498
51                O_Cancelled              A_Validating    345
52                O_Cancelled  O_Sent (mail and online)    338
55                O_Cancelled               A_Cancelled    260
66                O_Cancelled       W_Call after offers    100
80                O_Cancelled    W_Complete application     39
84                O_Cancelled                  A_Denied     33
87                O_Cancelled    W_Validate application     27
103               O_Cancelled      O_Sent (online only)     11
106               O_Cancelled              A_Incomplete      8
119               O_Cancelled                O_Returned      5
140               O_Cancelled                O_Accepted      1
0              O_Create Offer                 O_Created  42995
1                   O_Created  O_Sent (mail and online)  36212
25                  O_Created            O_Create Offer   3913
35                  O_Created      O_Sent (online only)   1920
44                  O_Created               O_Cancelled    760
62                  O_Created               A_Cancelled    119
82                  O_Created              A_Validating     35
88                  O_Created                  A_Denied     26
110                 O_Created              A_Incomplete      7
130                 O_Created    W_Validate application      2
150                 O_Created   W_Call incomplete files      1
37                  O_Refused    W_Validate application   1550
68                  O_Refused  W_Assess potential fraud     93
71                  O_Refused   W_Call incomplete files     68
91                  O_Refused       W_Call after offers     19
101                 O_Refused    W_Complete application     13
17                 O_Returned              A_Incomplete   7735
19                 O_Returned    W_Validate application   6355
20                 O_Returned                O_Accepted   5281
32                 O_Returned                  A_Denied   2190
38                 O_Returned              A_Validating   1396
65                 O_Returned            O_Create Offer    101
69                 O_Returned               A_Cancelled     73
73                 O_Returned   W_Call incomplete files     55
77                 O_Returned  W_Assess potential fraud     41
102                O_Returned               O_Cancelled     11
7    O_Sent (mail and online)    W_Complete application  18697
12   O_Sent (mail and online)                A_Complete  12215
31   O_Sent (mail and online)              A_Validating   3235
41   O_Sent (mail and online)               A_Cancelled   1038
47   O_Sent (mail and online)            O_Create Offer    675
50   O_Sent (mail and online)               O_Cancelled    387
56   O_Sent (mail and online)                O_Returned    251
90   O_Sent (mail and online)    W_Validate application     23
92   O_Sent (mail and online)              A_Incomplete     19
98   O_Sent (mail and online)                  A_Denied     15
99   O_Sent (mail and online)   W_Call incomplete files     14
121  O_Sent (mail and online)                O_Accepted      4
134  O_Sent (mail and online)       W_Call after offers      2
146  O_Sent (mail and online)      O_Sent (online only)      1
43       O_Sent (online only)              A_Validating    834
53       O_Sent (online only)    W_Complete application    335
54       O_Sent (online only)                O_Returned    272
60       O_Sent (online only)            O_Create Offer    154
61       O_Sent (online only)               A_Cancelled    134
63       O_Sent (online only)                A_Complete    115
86       O_Sent (online only)               O_Cancelled     31
95       O_Sent (online only)   W_Call incomplete files     18
100      O_Sent (online only)              A_Incomplete     13
105      O_Sent (online only)    W_Validate application      9
107      O_Sent (online only)                O_Accepted      8
116      O_Sent (online only)                  A_Denied      5
148      O_Sent (online only)  O_Sent (mail and online)      1
74   W_Assess potential fraud              A_Incomplete     53
79   W_Assess potential fraud                  A_Denied     41
81   W_Assess potential fraud    W_Validate application     38
96   W_Assess potential fraud            W_Handle leads     17
97   W_Assess potential fraud                O_Accepted     16
115  W_Assess potential fraud                A_Accepted      6
122  W_Assess potential fraud            O_Create Offer      4
127  W_Assess potential fraud       W_Call after offers      2
131  W_Assess potential fraud              A_Validating      2
133  W_Assess potential fraud               A_Cancelled      2
139  W_Assess potential fraud    W_Complete application      1
143  W_Assess potential fraud                O_Returned      1
147  W_Assess potential fraud                 A_Concept      1
57        W_Call after offers              A_Validating    207
33    W_Call incomplete files              A_Validating   2135
94    W_Call incomplete files               O_Cancelled     18
108   W_Call incomplete files  W_Assess potential fraud      7
128   W_Call incomplete files                  A_Denied      2
6      W_Complete application                A_Complete  19032
112    W_Complete application  W_Assess potential fraud      6
132    W_Complete application                A_Accepted      2
138    W_Complete application            O_Create Offer      1
28             W_Handle leads                 A_Concept   3493
14     W_Validate application              A_Incomplete  10790
42     W_Validate application               O_Cancelled    889
70     W_Validate application  W_Assess potential fraud     73
76     W_Validate application                  A_Denied     49
113    W_Validate application              A_Validating      6
136    W_Validate application                O_Accepted      1
137    W_Validate application                O_Returned      1

Probabilities

In [66]:
counts = branching_transitions.groupby(['concept:name', 'next_activity']).size().unstack(fill_value=0)
probabilities = counts.div(counts.sum(axis=1), axis=0)
decision_prob_rules = probabilities.to_dict(orient='index')
decision_prob_rules

{'A_Accepted': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.9998413151797899,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 6.347392808403948e-05,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 9.521089212605922e-05,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'A_Cancelled': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.9959270752521334,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0010667183863460046,
  'W_Call incomplete files': 0.0023273855702094647,
  'W_Complete application': 0.0006788207913110939,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'A_Complete': {'A_Accepted': 0.0,
  'A_Cancelled': 0.25641516660283414,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0034469551895825352,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.5853121409421678,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.015000638325035108,
  'O_Create Offer': 0.13197370100855355,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0013085663219711478,
  'O_Sent (online only)': 6.383250351078769e-05,
  'W_Assess potential fraud': 3.1916251755393846e-05,
  'W_Call after offers': 0.006447082854589557,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'A_Concept': {'A_Accepted': 0.9997461042876639,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 9.521089212605922e-05,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0001586848202100987,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'A_Create Application': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.35183598336983085,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.6481640166301692,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'A_Denied': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.996517546209483,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.001339405304045004,
  'W_Call incomplete files': 0.0008036431824270024,
  'W_Complete application': 0.0010715242432360033,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0002678810608090008},
 'A_Incomplete': {'A_Accepted': 0.0,
  'A_Cancelled': 0.03201146679407549,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0082091821222256,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.5334665334665335,
  'O_Accepted': 0.20766190331407722,
  'O_Cancelled': 0.004213178126221604,
  'O_Create Offer': 0.07401294357816098,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.050731876818833344,
  'O_Sent (mail and online)': 0.00017373930417408678,
  'O_Sent (online only)': 0.0002606089562611302,
  'W_Assess potential fraud': 4.3434826043521695e-05,
  'W_Call after offers': 4.3434826043521695e-05,
  'W_Call incomplete files': 0.08917169786735005,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'A_Pending': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.5085014409221902,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.008501440922190202,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.4829971181556196},
 'A_Submitted': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.8289183763404006,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.000881359251823924,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.17020026440777555,
  'W_Validate application': 0.0},
 'A_Validating': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0008759951562620771,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.028212196944322778,
  'A_Incomplete': 0.11405972225800634,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.1838559245613583,
  'O_Cancelled': 0.00018035194393631,
  'O_Create Offer': 0.0013139927343931157,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.5550202251822843,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 2.5764563419472856e-05,
  'W_Assess potential fraud': 0.0008244660294231314,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.11563136062659418},
 'O_Accepted': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 1.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'O_Cancelled': {'A_Accepted': 0.0,
  'A_Cancelled': 0.10752688172043011,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.013647642679900745,
  'A_Incomplete': 0.0033085194375516956,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.14267990074441686,
  'O_Accepted': 0.00041356492969396195,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.31141439205955335,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0020678246484698098,
  'O_Sent (mail and online)': 0.13978494623655913,
  'O_Sent (online only)': 0.004549214226633582,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0413564929693962,
  'W_Call incomplete files': 0.20595533498759305,
  'W_Complete application': 0.016129032258064516,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.011166253101736972},
 'O_Create Offer': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 1.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'O_Created': {'A_Accepted': 0.0,
  'A_Cancelled': 0.002767763693452727,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0006047214792417723,
  'A_Incomplete': 0.000162809629026631,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.000814048145133155,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.017676474008605652,
  'O_Create Offer': 0.09101058262588674,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.8422374694731946,
  'O_Sent (online only)': 0.04465635539016165,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 2.325851843237586e-05,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 4.651703686475172e-05},
 'O_Refused': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.05335628227194492,
  'W_Call after offers': 0.010900745840504877,
  'W_Call incomplete files': 0.03901319563970167,
  'W_Complete application': 0.007458405048766495,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.8892713711990821},
 'O_Returned': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0031414063172390053,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.09424218951717016,
  'A_Incomplete': 0.332859970737585,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.06007401669678974,
  'O_Accepted': 0.22725707892245461,
  'O_Cancelled': 0.00047336259574834325,
  'O_Create Offer': 0.004346329288234788,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0017643514932438248,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.002366812978741716,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.27347448145279285},
 'O_Sent (mail and online)': {'A_Accepted': 0.0,
  'A_Cancelled': 0.028379265091863518,
  'A_Complete': 0.3339621609798775,
  'A_Concept': 0.0,
  'A_Denied': 0.0004101049868766404,
  'A_Incomplete': 0.0005194663167104112,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.08844597550306212,
  'O_Accepted': 0.00010936132983377078,
  'O_Cancelled': 0.010580708661417323,
  'O_Create Offer': 0.018454724409448817,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.006862423447069116,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 2.7340332458442695e-05,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 5.468066491688539e-05,
  'W_Call incomplete files': 0.0003827646544181977,
  'W_Complete application': 0.5111821959755031,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.000628827646544182},
 'O_Sent (online only)': {'A_Accepted': 0.0,
  'A_Cancelled': 0.06946604458268534,
  'A_Complete': 0.05961638154484189,
  'A_Concept': 0.0,
  'A_Denied': 0.002592016588906169,
  'A_Incomplete': 0.00673924313115604,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.432348367029549,
  'O_Accepted': 0.00414722654224987,
  'O_Cancelled': 0.01607050285121825,
  'O_Create Offer': 0.07983411093831,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.1410057024364956,
  'O_Sent (mail and online)': 0.0005184033177812338,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.00933125972006221,
  'W_Complete application': 0.17366511145671332,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.004665629860031105},
 'W_Assess potential fraud': {'A_Accepted': 0.03260869565217391,
  'A_Cancelled': 0.010869565217391304,
  'A_Complete': 0.0,
  'A_Concept': 0.005434782608695652,
  'A_Denied': 0.22282608695652173,
  'A_Incomplete': 0.28804347826086957,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.010869565217391304,
  'O_Accepted': 0.08695652173913043,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.021739130434782608,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.005434782608695652,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.010869565217391304,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.005434782608695652,
  'W_Handle leads': 0.09239130434782608,
  'W_Validate application': 0.20652173913043478},
 'W_Call after offers': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 1.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'W_Call incomplete files': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.0009250693802035153,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.9875115633672525,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.008325624421831638,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0032377428307123032,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'W_Complete application': {'A_Accepted': 0.00010503650018381387,
  'A_Cancelled': 0.0,
  'A_Complete': 0.9995273357491729,
  'A_Concept': 0.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 5.2518250091906935e-05,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.00031510950055144165,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'W_Handle leads': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 1.0,
  'A_Denied': 0.0,
  'A_Incomplete': 0.0,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0,
  'O_Accepted': 0.0,
  'O_Cancelled': 0.0,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 0.0,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.0,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0},
 'W_Validate application': {'A_Accepted': 0.0,
  'A_Cancelled': 0.0,
  'A_Complete': 0.0,
  'A_Concept': 0.0,
  'A_Denied': 0.004149377593360996,
  'A_Incomplete': 0.9137098822931662,
  'A_Pending': 0.0,
  'A_Submitted': 0.0,
  'A_Validating': 0.0005080870522482852,
  'O_Accepted': 8.46811753747142e-05,
  'O_Cancelled': 0.07528156490812092,
  'O_Create Offer': 0.0,
  'O_Created': 0.0,
  'O_Refused': 0.0,
  'O_Returned': 8.46811753747142e-05,
  'O_Sent (mail and online)': 0.0,
  'O_Sent (online only)': 0.0,
  'W_Assess potential fraud': 0.006181725802354137,
  'W_Call after offers': 0.0,
  'W_Call incomplete files': 0.0,
  'W_Complete application': 0.0,
  'W_Handle leads': 0.0,
  'W_Validate application': 0.0}}

Save the probabilities as a csv file

In [67]:
output_file = "decision_prob_rules.json"
with open(output_file, "w") as f:
    json.dump(decision_prob_rules, f, indent=4)

Debug the test_output.csv

In [74]:
import pandas as pd

df = pd.read_csv('/Users/zeynepcetin/bppso-groupwork-1/test_output.csv')
decision_step = 'A_Cancelled'

df = df.sort_values(by=['case:concept:name', 'time:timestamp'])
df['next'] = df.groupby('case:concept:name')['concept:name'].shift(-1)
print(df[df['concept:name'] == decision_step]['next'].value_counts(normalize=True))

next
O_Cancelled       0.773333
O_Create Offer    0.160000
O_Created         0.053333
A_Complete        0.013333
Name: proportion, dtype: float64

In [76]:
import pandas as pd

df = pd.read_csv('/Users/zeynepcetin/bppso-groupwork-1/test_output.csv')

if 'lifecycle:transition' in df.columns:
    df = df[df['lifecycle:transition'].str.lower() == 'complete']

df = df.sort_values(by=['case:concept:name', 'time:timestamp'])
df['next_activity'] = df.groupby('case:concept:name')['concept:name'].shift(-1)

unique_activities = df['concept:name'].unique()

for activity in unique_activities:
    transitions = df[df['concept:name'] == activity]['next_activity']
    
    if transitions.dropna().empty:
        continue

    probs = transitions.value_counts(normalize=True)
    
    print(f"'{activity}':")
    for target, prob in probs.items():
        print(f"    {target}: {prob:.5f}")
    print("")

'A_Create Application':
    A_Submitted: 1.00000

'A_Submitted':
    W_Handle leads: 1.00000

'W_Handle leads':
    A_Concept: 1.00000

'A_Concept':
    W_Complete application: 1.00000

'W_Complete application':
    A_Accepted: 1.00000

'A_Accepted':
    O_Create Offer: 1.00000

'O_Create Offer':
    O_Created: 1.00000

'O_Created':
    O_Sent (mail and online): 0.96891
    O_Cancelled: 0.03109

'O_Sent (mail and online)':
    A_Complete: 1.00000

'A_Complete':
    W_Call after offers: 1.00000

'W_Call after offers':
    A_Validating: 1.00000

'A_Validating':
    W_Validate application: 1.00000

'W_Validate application':
    O_Returned: 1.00000

'O_Returned':
    A_Incomplete: 0.54427
    O_Accepted: 0.32812
    A_Denied: 0.12500
    W_Call incomplete files: 0.00260

'O_Accepted':
    A_Pending: 1.00000

'A_Pending':
    O_Cancelled: 1.00000

'O_Cancelled':
    O_Create Offer: 0.98529
    A_Cancelled: 0.01471

'A_Incomplete':
    W_Call incomplete files: 0.99519
    A_Validating: 0.00481

'W_Call incomplete files':
    A_Validating: 0.98558
    O_Cancelled: 0.00962
    A_Incomplete: 0.00481

'A_Denied':
    O_Refused: 1.00000

'A_Cancelled':
    O_Cancelled: 1.00000

+ Where the Decision Manager works: 
A_Accepted, O_Create Offer, O_Accepted, A_Denied, A_Cancelled
- middle
A_Pending, W_Call after offers, A_Complete, O_Sent (mail and online), A_Validating
- problematic
A_Create Application, A_Submitted, A_Concept, W_C a, O_Created, W_Validate application
A_Pending

In [77]:
df_out = pd.read_csv('/Users/zeynepcetin/bppso-groupwork-1/test_output.csv')

if 'lifecycle:transition' in df_out.columns:
    df_out = df_out[df_out['lifecycle:transition'].str.lower() == 'complete']

distinct_activities = sorted(df_out['concept:name'].dropna().unique())

print(f"Number of distinct activities: {len(distinct_activities)}\n")
for a in distinct_activities:
    print(a)

Number of distinct activities: 22

A_Accepted
A_Cancelled
A_Complete
A_Concept
A_Create Application
A_Denied
A_Incomplete
A_Pending
A_Submitted
A_Validating
O_Accepted
O_Cancelled
O_Create Offer
O_Created
O_Refused
O_Returned
O_Sent (mail and online)
W_Call after offers
W_Call incomplete files
W_Complete application
W_Handle leads
W_Validate application

In [79]:
activity_counts = (
    df_out['concept:name']
    .value_counts()
    .reset_index()
    .rename(columns={'index': 'activity', 'concept:name': 'count'})
)
display(activity_counts)

                       count  count
0               A_Validating    392
1     W_Validate application    391
2                 O_Returned    385
3               A_Incomplete    210
4    W_Call incomplete files    208
5             O_Create Offer    193
6                  O_Created    193
7   O_Sent (mail and online)    187
8                 A_Complete    187
9        W_Call after offers    186
10               O_Cancelled    136
11                 A_Pending    126
12                O_Accepted    126
13      A_Create Application    100
14               A_Submitted     62
15            W_Handle leads     62
16    W_Complete application     60
17                 A_Concept     60
18                A_Accepted     59
19                  A_Denied     48
20                 O_Refused     48
21               A_Cancelled      2